services:
  linkding:
    image: sissbruecker/linkding:latest
    container_name: linkding
    ports:
      - "9090:9090"
    volumes:
      - ./data:/etc/linkding/data
    env_file:
      - .env
    restart: unless-stopped
  echo-link:
    build:
      context: .
      dockerfile: Dockerfile
    # image: huffmanks/echo-link@latest
    container_name: echo-link
    ports:
      - "3000:80"
    environment:
      - LINKDING_INTERNAL=http://linkding:9090 # this must match linkding container name and port above
    restart: unless-stopped
