services:
  echo-link:
    build:
      context: .
      dockerfile: Dockerfile
    image: echo-link
    container_name: echo-link
    ports:
      - "3000:3000"
    environment:
      VITE_LINKDING_URL: ${VITE_LINKDING_URL}
      VITE_LINKDING_API_TOKEN: ${VITE_LINKDING_API_TOKEN}
    restart: unless-stopped
