services:
  linkding:
    image: sissbruecker/linkding:latest
    container_name: linkding
    ports:
      - "9090:9090"
    volumes:
      - ./data:/etc/linkding/data
    environment:
      LD_SUPERUSER_NAME: ${LD_SUPERUSER_NAME}
      LD_SUPERUSER_PASSWORD: ${LD_SUPERUSER_PASSWORD}
      LD_USE_X_FORWARDED_HOST: "true"
      LD_CSRF_TRUSTED_ORIGINS: http://${APP_DOMAIN}:${APP_PORT:-3000}
    restart: unless-stopped
  echo-link:
    build:
      context: .
      dockerfile: Dockerfile
    # image: huffmanks/echo-link@latest
    container_name: echo-link
    ports:
      - "${APP_PORT:-3000}:8080"
    depends_on:
      - linkding
    restart: unless-stopped
